name: Build & Release (PROD)

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger for production releases

permissions:
  id-token: write
  contents: read

jobs:
  release:
    uses: ./.github/workflows/ecr-push.yml
    with:
      environment: production
    secrets: inherit
