name: Build & Release (PROD)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  production-release:
    name: Build & Release [PROD]
    uses: ./.github/workflows/ecr-push.yml
    with:
      environment: prod
    secrets: inherit
