name: Build & Release (DEV)

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  development-release:
    name: Build & Release [DEV]
    uses: ./.github/workflows/ecr-push.yml
    with:
      environment: dev
    secrets: inherit
