name: Build Docker Container , Push to ECR Registry & Rollout

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag (Required during run, e.g., v1.2.0)'
        required: true
        type: string
  push:
    branches: [ "main", "develop" ]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
      
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: apikey
            context: ./apikey
            dockerfile: ./apikey/Dockerfile
          - service: jwt
            context: ./jwt
            dockerfile: ./jwt/Dockerfile
          - service: oidc-app
            context: ./oidc
            dockerfile: ./oidc/Dockerfile.app
          - service: mock-idp
            context: ./oidc
            dockerfile: ./oidc/Dockerfile.idp

    steps:

    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build and Push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        SERVICE: ${{ matrix.service }}
        CUSTOM_TAG: ${{ github.event.inputs.tag }}
      run: |
        # In this mode, we ONLY care about manual execution
        if [[ -z "$CUSTOM_TAG" ]]; then
          echo "⚠️ No Manager Release Tag provided. Skipping Build & Push entirely."
          exit 0
        fi

        IMAGE_TAG=$CUSTOM_TAG
        echo "🏷️ Building Release Tag: $IMAGE_TAG"
        
        echo "🚀 Building $SERVICE..."
        docker build -t $ECR_REGISTRY/$SERVICE:$IMAGE_TAG -f ${{ matrix.dockerfile }} ${{ matrix.context }}
        
        echo "📤 Pushing $SERVICE:$IMAGE_TAG to ECR..."
        docker push $ECR_REGISTRY/$SERVICE:$IMAGE_TAG