name: Build Docker Container , Push to ECR Registry & Rollout

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "main", "develop" ]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # needs: [fastapi_app_test]

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout


    steps:

    - name: Check out code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2